Add logs for debug server down
starhugegraph/hugegraph pull request #89
Opened 2021-11-25 11:57 UTC by Scorpiour

Add access logger to inspect rest-api access
Adjust log4j format from text pattern to json with custom timestamp

2021-11-25 12:50 UTC, david-sunw approved these changes

2021-11-26 03:35 UTC, zhoney requested changes

2021-11-26 03:35 UTC, zhoney commented on hugegraph-api/src/main/java/com/baidu/hugegraph/api/profile/VersionAPI.java
> +
delete empty line

2021-11-26 03:35 UTC, zhoney commented on hugegraph-core/src/main/java/com/baidu/hugegraph/StandardHugeGraph.java
> +
ditto

2021-11-26 03:35 UTC, zhoney commented on hugegraph-core/src/main/java/com/baidu/hugegraph/task/TaskManager.java
> +import com.baidu.hugegraph.util.*;
don't use wild pattern, every import class one line

2021-11-26 03:35 UTC, zhoney commented on hugegraph-api/src/main/java/com/baidu/hugegraph/api/filter/AccessLogFilter.java
> +    public void filter(ContainerRequestContext requestContext, ContainerResponseContext responseContext) throws IOException {
improve align, we prefer not exceed 80 chars per line

2021-12-17 11:49 UTC, zhoney approved these changes

2021-12-17 11:50 UTC, merged